import Minion from '../entities/minion.js';

export default {
  target: 'caster',
  name: 'Summon Draugr Mage',
  type: 'Summons',
  details:
    'Summons a low level undead spellcaster to toil for you. Increases the rate of mana automatically regenerated by 1 per Draugr Mage.',
  manaCost: 20,
  healthCost: 20,
  goldCost: 20,
  effect: function () {
    this.caster.addMinion(
      new Minion({
        name: 'Draugr Mage',
        type: 'draugr',
        role: 'labor',
        resource: 'mana',
        means: 'regen',
        boost: 1,
      })
    );
  },
};
