import Minion from '../entities/minion.js';

export default {
  target: 'caster',
  name: 'Summon Skeletal Priest',
  type: 'Summons',
  details:
    'Summons the lowest level of undead priest to toil for you. Increases the rate of health regenerated by 1 per Skeletal Priest.',
  manaCost: 10,
  healthCost: 25,
  goldCost: 10,
  effect: function () {
    this.caster.addMinion(
      new Minion({
        name: 'Skeletal Priest',
        type: 'skeleton',
        role: 'labor',
        resource: 'health',
        means: 'regen',
        boost: 1,
      })
    );
  },
};
